fastlane_version "1.53.0"

default_platform :ios

platform :ios do

  before_all do
  end

  desc "Run all the tests"
  lane :test do
    scan(
	     scheme: "iOS",
	     device: "iPhone 6s (9.2)"
    )    
  end

  after_all do |lane|
    notify "Fastlane '#{lane}' finished" # Mac OS X Notification
  end

  error do |lane, exception|
    notify "Fastlane '#{lane}' errored" # Mac OS X Notification
  end

end