fastlane_version "1.54.0"

default_platform :ios

platform :ios do

  ############################## PRE ##############################

  before_all do
    ensure_git_status_clean
  end

  ########################### ACTIONS #############################

  desc "Runs all the unit and ui tests"
  lane :test do
      scan
  end

  ############################# POST ##############################

  after_all do |lane|  
    notification(subtitle: "Finished Building: '#{lane}'", message: "Success")
  end

  error do |lane, exception|
    notification(subtitle: "Error building Building: '#{lane}'", message: "Error")
  end

end